name: Node Ci Start

on: push

# jobs: 
#   say-hello: 
#     runs-on: ubuntu-latest

#     steps:
#       - name: print message
#         run: echo "first devops pipeline"

#       - name: step - 1 get code
#         uses: actions/checkout@v4

#       - name: step - 2 install node
#         uses: actions/setup-node@v3
#         with: 
#           node-version: '18'
        
#       - name: step - 4 run app
#         run: node app.js

jobs:
  test-name:
    runs-on: ubuntu-latest
    
    env:
      name: ${{secrets.MY_NAME}}

    steps: 
      - name: print Name
        run: echo "Hello , ${{env.name}}"

  test:
    runs-on: ubuntu-latest
    
    steps:
      - name : get code
        uses : actions/checkout@v4

      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
        
      - name: install dependencies 
        run: npm ci

      - name: run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
        os: [ubuntu-latest, windows-latest]
    needs: test
    steps: 
      - name: get code
        uses: actions/checkout@v4

      - name: setup - node
        uses: actions/setup-node@v4
        with:
          node-version: $ {{matrix.node-version}}
          cache: 'npm'


      
      - name: install dependencies
        run: npm ci
        
      - name: build app
        run: npm run build

      - name: run app
        env: 
          MY_NAME: ${{secrets.MY_NAME}}

        run: npm start

